repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.1
    hooks:
      - id: golangci-lint-full
  - repo: https://github.com/matthewhughes934/golines
    rev: v0.12.0
    hooks:
      - id: golines
  - repo: https://gitlab.com/matthewhughes/go-pre-commit
    rev: v0.2.0
    hooks:
      - id: go-mod-tidy
