repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.63.4
    hooks:
      - id: golangci-lint-full
      - id: golangci-lint-config-verify
  - repo: https://github.com/segmentio/golines
    rev: fc305205784a70b4cfc17397654f4c94e3153ce4
    hooks:
      - id: golines
  - repo: https://gitlab.com/matthewhughes/go-pre-commit
    rev: v0.3.0
    hooks:
      - id: go-mod-tidy
