repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
      - id: golangci-lint-full
      - id: golangci-lint-config-verify
  - repo: https://github.com/matthewhughes934/golines
    rev: v0.12.0
    hooks:
      - id: golines
  - repo: https://gitlab.com/matthewhughes/go-pre-commit
    rev: v0.3.0
    hooks:
      - id: go-mod-tidy
